spring:
  application:
    name: server
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/clean_stream
    username: postgres
    password: 90eugine
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/clean_stream}
  
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

n8n:
  webhook:
    url: https://koyo.app.n8n.cloud/webhook/clean-data

# FastAPI AI Engine configuration
fastapi:
  base-url: http://localhost:8000

server:
  port: 8080

# Logging
logging:
  level:
    root: INFO
    com.server.server: DEBUG
    org.hibernate.SQL: DEBUG
